### ISSUE TITLE
JsonPropertyNamingStrategy 동작하지 않는 이슈

### ISSUE THREAD

**Issue by im-gnar** [hometerview/Server#21]
### Describe Bug
JsonPropertyNamingStrategy Config 설정이 적용되지 않아 수동으로 `@JsonProperties` 혹은 `@JsonNaming`을 추가해줘야함

### TODO
- [ ] Camel to Snake Case 이슈 해결
- [ ] MongoDB 데이터 재삽입
- [ ] MongoTemplate 쿼리 수정

**Comment by CODe5753** [comment]
공유 감사합니다👍
해당 설정을 어떤 것을 적용해보았는지 커밋 내역이나 코드 일부를 공유해주시면 좋을 것 같아요🙏🏻
